import type { ResumeData } from "./index";

export const sampleResume: ResumeData = {
  basics: {
    name: "Jean Dupont",
    headline: "Développeur Web Créatif et Innovant",
    email: "jean.dupont@gmail.com",
    phone: "06 00 00 00 00",
    location: "Nice, 06000",
    url: {
      label: "",
      href: "https://jeandupont.me/",
    },
    customFields: [],
    picture: {
      url: "https://i.imgur.com/HgwyOuJ.jpg",
      size: 120,
      aspectRatio: 1,
      borderRadius: 0,
      effects: {
        hidden: false,
        border: false,
        grayscale: false,
      },
    },
  },
  sections: {
    summary: {
      name: "Résumé",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "summary",
      content:
        "<p>Développeur Web innovant avec 5 ans d'expérience dans la création de sites et d'applications percutants et conviviaux. Spécialisé dans les <strong>technologies front-end</strong> et passionné par les standards modernes du web et les techniques de développement de pointe. Expérience avérée dans la conduite de projets réussis de la conception au déploiement.</p>",
    },
    awards: {
      name: "Récompenses",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "awards",
      items: [],
    },
    certifications: {
      name: "Certifications",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "certifications",
      items: [
        {
          id: "spdhh9rrqi1gvj0yqnbqunlo",
          visible: true,
          name: "Développement Web Full-Stack",
          issuer: "CodeAcademy",
          date: "2020",
          summary: "",
          url: {
            label: "",
            href: "",
          },
        },
        {
          id: "n838rddyqv47zexn6cxauwqp",
          visible: true,
          name: "Développeur Certifié AWS",
          issuer: "Amazon Web Services",
          date: "2019",
          summary: "",
          url: {
            label: "",
            href: "",
          },
        },
      ],
    },
    education: {
      name: "Formation",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "education",
      items: [
        {
          id: "yo3p200zo45c6cdqc6a2vtt3",
          visible: true,
          institution: "Université de Californie",
          studyType: "Licence en Informatique",
          area: "Berkeley, CA",
          score: "",
          date: "Août 2012 à Mai 2016",
          summary: "",
          url: {
            label: "",
            href: "",
          },
        },
      ],
    },
    experience: {
      name: "Expériences Professionnelles",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "experience",
      items: [
        {
          id: "lhw25d7gf32wgdfpsktf6e0x",
          visible: true,
          company: "Creative Solutions Inc.",
          position: "Développeur Web Senior",
          location: "San Francisco, CA",
          date: "Janvier 2019 à Aujourd’hui",
          summary:
            "<ul><li><p>Dirigé la refonte du site produit principal, augmentant l'engagement utilisateur de 40%.</p></li><li><p>Développé et mis en œuvre un nouveau framework responsive, améliorant la compatibilité multi-appareils.</p></li><li><p>Encadré une équipe de quatre développeurs juniors, favorisant une culture d'excellence technique.</p></li></ul>",
          url: {
            label: "",
            href: "https://creativesolutions.inc/",
          },
        },
        {
          id: "r6543lil53ntrxmvel53gbtm",
          visible: true,
          company: "TechAdvancers",
          position: "Développeur Web",
          location: "San Jose, CA",
          date: "Juin 2016 à Décembre 2018",
          summary:
            "<ul><li><p>Travaillé en équipe de 10 pour développer des applications web de haute qualité en React.js et Node.js.</p></li><li><p>Géré l'intégration de services tiers tels que Stripe pour les paiements et Twilio pour les SMS.</p></li><li><p>Optimisé les performances des applications, réduisant les temps de chargement de 30%.</p></li></ul>",
          url: {
            label: "",
            href: "https://techadvancers.com/",
          },
        },
      ],
    },
    volunteer: {
      name: "Bénévolat",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "volunteer",
      items: [],
    },
    interests: {
      name: "Centres d’intérêt",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "interests",
      items: [],
    },
    languages: {
      name: "Langues",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "languages",
      items: [],
    },
    profiles: {
      name: "Portfolio",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "profiles",
      items: [
        {
          id: "cnbk5f0aeqvhx69ebk7hktwd",
          visible: true,
          network: "LinkedIn",
          username: "jeandupont",
          icon: "linkedin",
          url: {
            label: "",
            href: "https://linkedin.com/in/jeandupont",
          },
        },
        {
          id: "ukl0uecvzkgm27mlye0wazlb",
          visible: true,
          network: "GitHub",
          username: "jeandupont",
          icon: "github",
          url: {
            label: "",
            href: "https://github.com/jeandupont",
          },
        },
      ],
    },
    projects: {
      name: "Projets",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "projects",
      items: [
        {
          id: "yw843emozcth8s1ubi1ubvlf",
          visible: true,
          name: "Plateforme E-Commerce",
          description: "Chef de projet",
          date: "",
          summary:
            "<p>Dirigé le développement d’une plateforme e-commerce full-stack, augmentant le taux de conversion de 25%.</p>",
          keywords: [],
          url: {
            label: "",
            href: "",
          },
        },
        {
          id: "ncxgdjjky54gh59iz2t1xi1v",
          visible: true,
          name: "Tableau de bord interactif",
          description: "Développeur Frontend",
          date: "",
          summary:
            "<p>Créé un tableau de bord analytique interactif pour une application SaaS, améliorant la visualisation des données pour les clients.</p>",
          keywords: [],
          url: {
            label: "",
            href: "",
          },
        },
      ],
    },
    publications: {
      name: "Publications",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "publications",
      items: [],
    },
    references: {
      name: "Références",
      columns: 1,
      separateLinks: true,
      visible: false,
      id: "references",
      items: [
        {
          id: "f2sv5z0cce6ztjl87yuk8fak",
          visible: true,
          name: "Disponible sur demande",
          description: "",
          summary: "",
          url: {
            label: "",
            href: "",
          },
        },
      ],
    },
    skills: {
      name: "Compétences",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "skills",
      items: [
        {
          id: "hn0keriukh6c0ojktl9gsgjm",
          visible: true,
          name: "Technologies Web",
          description: "Avancé",
          level: 0,
          keywords: ["HTML5", "JavaScript", "PHP", "Python"],
        },
        {
          id: "r8c3y47vykausqrgmzwg5pur",
          visible: true,
          name: "Frameworks Web",
          description: "Intermédiaire",
          level: 0,
          keywords: ["React.js", "Angular", "Vue.js", "Laravel", "Django"],
        },
        {
          id: "b5l75aseexqv17quvqgh73fe",
          visible: true,
          name: "Outils",
          description: "Intermédiaire",
          level: 0,
          keywords: ["Webpack", "Git", "Jenkins", "Docker", "JIRA"],
        },
      ],
    },
    custom: {},
  },
  metadata: {
    template: "Captain America",
    layout: [
      [
        ["summary", "experience", "education", "projects", "references"],
        [
          "profiles",
          "skills",
          "certifications",
          "interests",
          "languages",
          "awards",
          "volunteer",
          "publications",
        ],
      ],
    ],
    css: {
      value: "* {\n\toutline: 1px solid #000;\n\toutline-offset: 4px;\n}",
      visible: false,
    },
    page: {
      margin: 14,
      format: "a4",
      options: {
        breakLine: true,
        pageNumbers: true,
      },
    },
    theme: {
      background: "#ffffff",
      text: "#000000",
      primary: "#4cccb8",
    },
    typography: {
      font: {
        family: "Josefin Sans",
        subset: "latin",
        variants: ["regular"],
        size: 13,
      },
      lineHeight: 1.6,
      hideIcons: false,
      underlineLinks: true,
    },
    notes: "",
  },
};
