import type { ResumeData } from "./index";

export const sampleResume: ResumeData = {
  basics: {
    name: "Jean Dupont",
    headline: "Développeur Web Créatif et Innovant",
    email: "jean.dupont@gmail.com",
    phone: "06 00 00 00 00",
    location: "Nice, 06000",
    portfolio: {
      label: "",
      href: "https://mon-site-perso.fr/",
    },
    customFields: [],
    picture: {
      url: "https://i.imgur.com/IZm1zJx.jpeg",
      size: 140,
      aspectRatio: 1,
      borderRadius: 4,
      effects: {
        hidden: false,
        border: false,
        grayscale: false,
      },
    },
    birthday: "01-01-2000",
  },
  sections: {
    summary: {
      name: "Phrase d'Accroche",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "summary",
      content:
        "<p>Étudiant en développement web à la recherche d'une alternance de 12 mois (4 jours en entreprise, 1 jour en cours) dès septembre.</p>",
    },
    awards: {
      name: "Récompenses",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "awards",
      items: [],
    },
    certifications: {
      name: "Certifications",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "certifications",
      items: [
        {
          id: "spdhh9rrqi1gvj0yqnbqunlo",
          visible: true,
          name: "Développement Web Full-Stack",
          issuer: "CodeAcademy",
          date: "2020",
          summary: "",
          url: {
            label: "",
            href: "",
          },
        },
        {
          id: "n838rddyqv47zexn6cxauwqp",
          visible: true,
          name: "Développeur Certifié AWS",
          issuer: "Amazon Web Services",
          date: "2019",
          summary: "",
          url: {
            label: "",
            href: "",
          },
        },
      ],
    },
    education: {
      name: "Formations",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "education",
      items: [
        {
          id: "yo3p200zo45c6cdqc6a2vtt3",
          visible: true,
          institution: "AcadéNice",
          studyType: "Parcours Développement Web & Web Mobile",
          area: "Nice, France",
          score: "",
          date: "Septembre 2023 à Juin 2024",
          summary:
            "Apprentissage intensif des technologies front-end et back-end modernes, réalisation de projets concrets en équipe et préparation au monde professionnel.",
          url: {
            label: "acadenice.fr",
            href: "https://acadenice.fr/parcours-de-formation/developpement-web-et-web-mobile/",
          },
        },
      ],
    },
    experience: {
      name: "Expériences Professionelles",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "experience",
      items: [
        {
          id: "lhw25d7gf32wgdfpsktf6e0x",
          visible: true,
          company: "Start-up locale (Freelance / Stage)",
          position: "Développeur Web Junior",
          location: "Nice, France",
          date: "Avril 2024 à Juin 2024",
          summary:
            "<ul><li><p>Participation à la création d’un site vitrine responsive sous React.js pour un commerce local.</p></li><li><p>Intégration d’un back-office avec Node.js et MongoDB.</p></li><li><p>Travail en équipe agile et utilisation de Git pour la gestion de version.</p></li></ul>",
          url: {
            label: "",
            href: "",
          },
        },
      ],
    },
    volunteer: {
      name: "Bénévolat",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "volunteer",
      items: [],
    },
    interests: {
      name: "Centres d’intérêt",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "interests",
      items: [
        {
          id: "g4m1n9c0d3r1nt3r3st1",
          visible: true,
          name: "Jeux vidéo",
          keywords: ["Esport", "Stratégie", "RPG", "Indie Games"],
        },
        {
          id: "w3bcr34t0r1nt3r3st2",
          visible: true,
          name: "Création de sites web",
          keywords: ["Design", "WordPress", "No-code", "SEO"],
        },
        {
          id: "c0d1ngch4ll3ng31nt3r3st3",
          visible: true,
          name: "Coding Challenges",
          keywords: ["LeetCode", "Codewars", "Hackathons"],
        },
        {
          id: "t3chw4tch1nt3r3st4",
          visible: true,
          name: "Veille technologique",
          keywords: ["Nouvelles technologies", "Startups", "IA", "Web3"],
        },
        {
          id: "str34m1ng1nt3r3st5",
          visible: true,
          name: "Streaming & Création de contenu",
          keywords: ["Twitch", "YouTube", "Montage vidéo"],
        },
      ],
    },
    languages: {
      name: "Langues",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "languages",
      items: [
        {
          id: "l1k2j3h4g5f6d7s8a9q0w1e2",
          visible: true,
          name: "Anglais",
          description: "",
          level: 4,
        },
        {
          id: "l1k2j3h4g5f6d7s8a9q0w1e2",
          visible: true,
          name: "Italien",
          description: "",
          level: 3,
        },
      ],
    },
    socials: {
      name: "Réseaux Sociaux",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "socials",
      items: [
        {
          id: "cnbk5f0aeqvhx69ebk7hktwd",
          visible: true,
          network: "LinkedIn",
          username: "jeandupont",
          icon: "linkedin",
          url: {
            label: "",
            href: "https://linkedin.com/in/jeandupont",
          },
        },
        {
          id: "ukl0uecvzkgm27mlye0wazlb",
          visible: true,
          network: "GitHub",
          username: "jeandupont",
          icon: "github",
          url: {
            label: "",
            href: "https://github.com/jeandupont",
          },
        },
      ],
    },
    projects: {
      name: "Projets",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "projects",
      items: [
        {
          id: "ncxgdjjky54gh59iz2t1xi1v",
          visible: true,
          name: "Projet Étudiant - AcadéNice",
          description: "Développeur Front-End",
          date: "Janvier 2024 à Mars 2024",
          summary:
            "<p>Conception et développement d’une application de gestion de tâches en React.js et Tailwind CSS. Collaboration avec une équipe de 4 étudiants et mise en place d’une API REST pour la gestion des données.</p>",
          keywords: [],
          url: {
            label: "",
            href: "",
          },
        },
      ],
    },
    publications: {
      name: "Publications",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "publications",
      items: [],
    },
    references: {
      name: "Références",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "references",
      items: [
        {
          id: "f2sv5z0cce6ztjl87yuk8fak",
          visible: true,
          name: "Disponible sur demande",
          description: "",
          summary: "",
          url: {
            label: "",
            href: "",
          },
        },
      ],
    },
    hardSkills: {
      name: "Savoirs-Faire",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "hardSkills",
      items: [
        {
          id: "hn0keriukh6c0ojktl9gsgjm",
          visible: true,
          name: "Technologies Web",
          description: "Avancé",
          level: 0,
          keywords: ["HTML5", "JavaScript", "PHP", "Python"],
        },
        {
          id: "r8c3y47vykausqrgmzwg5pur",
          visible: true,
          name: "Frameworks Web",
          description: "Intermédiaire",
          level: 0,
          keywords: ["React.js", "Angular", "Vue.js", "Laravel", "Django"],
        },
        {
          id: "b5l75aseexqv17quvqgh73fe",
          visible: true,
          name: "Outils",
          description: "Intermédiaire",
          level: 0,
          keywords: ["Webpack", "Git", "Jenkins", "Docker", "JIRA"],
        },
      ],
    },
    softSkills: {
      name: "Savoirs-Êtres",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "softSkills",
      items: [
        {
          id: "x1n8vj5pmcz4u1a0g2h3ykbd",
          visible: true,
          name: "Travail en équipe",
        },
        {
          id: "w7k9ph0uz5s2f3dq8n6jrb1v",
          visible: true,
          name: "Autonomie",
        },
        {
          id: "q4h2l8nx0f7m9e5r1v6tbzdu",
          visible: true,
          name: "Adaptabilité",
        },
        {
          id: "p9c3t1fs8m2v6y7hj4l0xqnb",
          visible: true,
          name: "Sens de l’analyse",
        },
        {
          id: "r5z7y2kd0v1h8pl3c9n6bxmw",
          visible: true,
          name: "Créativité",
        },
      ],
    },
    custom: {},
  },
  metadata: {
    template: "Ant Man",
    layout: [
      [
        [
          "socials",
          "summary",
          "experience",
          "education",
          "projects",
          "volunteer",
          "certifications",
        ],
        [
          "hardSkills",
          "softSkills",
          "interests",
          "awards",
          "publications",
          "languages",
          "references",
        ],
      ],
    ],
    css: {
      value: "* {\n\toutline: 1px solid #000;\n\toutline-offset: 4px;\n}",
      visible: false,
    },
    page: {
      margin: 14,
      format: "a4",
      options: {
        breakLine: true,
        pageNumbers: true,
      },
    },
    theme: {
      background: "#ffffff",
      text: "#000000",
      primary: "#4cccb8",
    },
    typography: {
      font: {
        family: "Josefin Sans",
        subset: "latin",
        variants: ["regular"],
        size: 13,
      },
      lineHeight: 1.75,
      hideIcons: false,
      underlineLinks: true,
    },
    notes: "",
  },
};
